# Generated by Django 5.1.1 on 2024-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_about_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('job_name', models.CharField(max_length=250)),
                ('job_place', models.CharField(max_length=250)),
                ('start_year', models.IntegerField(default=0)),
                ('finish_year', models.IntegerField(default=0)),
            ],
        ),
    ]
