# Generated by Django 5.1.1 on 2024-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
