# Generated by Django 5.2.1 on 2025-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_year',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.CharField(max_length=250),
        ),
    ]
