# Generated by Django 5.2.1 on 2025-06-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_experience_finish_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone',
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='education',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
