# Generated by Django 5.2.1 on 2025-06-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_about_email_remove_about_phone_about_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='eng_description',
            field=models.TextField(default='No description', null=True),
        ),
    ]
