# Generated by Django 5.2.1 on 2025-06-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_about_eng_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='telegram',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
