# Generated by Django 5.2.1 on 2025-06-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_about_github_about_linkedin_about_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='desc',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='goals',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
