# Generated by Django 5.2.1 on 2025-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_about_desc_about_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AddField(
            model_name='about',
            name='desc2',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc3',
            field=models.TextField(default='No Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='desc4',
            field=models.TextField(default='No Description'),
        ),
    ]
