# Generated by Django 5.2.1 on 2025-06-25 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_desc_about_desc1_about_desc2_about_desc3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='photo',
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.projects')),
            ],
        ),
    ]
